<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            [
                'id' => 520,
                'name' => 'Abraham',
                'first_last_name' => 'Hernandez',
                'second_last_name' => 'Fernandez',
                'email' => 'abraham.hernandez@ldrsolutions.com.mx',
                'type_user' => 1,
                'type_person' => 4,
                'phone' => '0123456789',
                'collaborator_number' => '240520',
                'birth_date' => '1982-01-21',
                'curp' => 'HEFA820121HHGRRB02',
                'rfc' => 'HEFA820121IE3',
                'razon_social' => null,
                'representante_legal' => null,
                'domicilio_fiscal' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'password' => Hash::make('password'),
            ],
            [
                'id' => 547,
                'name' => 'Pedro',
                'first_last_name' => 'Leyva',
                'second_last_name' => 'Ojeda',
                'email' => 'pedro.leyva@ldrsolutions.com.mx',
                'type_user' => 2,
                'type_person' => 4,
                'phone' => '0123456789',
                'collaborator_number' => '240547',
                'birth_date' => '1972-03-09',
                'curp' => 'LEOP720309HQTYJD01',
                'rfc' => 'LEOP720309PT7',
                'razon_social' => null,
                'representante_legal' => null,
                'domicilio_fiscal' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'password' => Hash::make('password'),
            ],
            [
                'id' => 676,
                'name' => 'David',
                'first_last_name' => 'Bernal',
                'second_last_name' => 'Bernal',
                'email' => 'david.bernal@ldrsolutions.com.mx',
                'type_user' => 2,
                'type_person' => 4,
                'phone' => '0123456789',
                'collaborator_number' => '250669',
                'birth_date' => '1982-05-14',
                'curp' => 'BEBD820514HMCRRV04',
                'rfc' => 'BEBD820514IF7',
                'razon_social' => null,
                'representante_legal' => null,
                'domicilio_fiscal' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'password' => Hash::make('password'),
            ],
            [
                'id' => 1,
                'name' => null,
                'first_last_name' => null,
                'second_last_name' => null,
                'email' => 'luis.espinoza@ldrsolutions.com.mx',
                'type_user' => 1,
                'type_person' => 5,
                'phone' => '0123456789',
                'collaborator_number' => null,
                'birth_date' => null,
                'curp' => null,
                'rfc' => 'EIML031227HLD',
                'razon_social' => 'LDR Solutions',
                'representante_legal' => 'CEO',
                'domicilio_fiscal' => 'Santa Fe',
                'created_at' => now(),
                'updated_at' => now(),
                'password' => Hash::make('password'),
            ],
            [
                'id' => 2,
                'name' => 'Luis Angel',
                'first_last_name' => 'Espinoza',
                'second_last_name' => 'Mauro',
                'email' => 'luisangelem.dp@gmail.com',
                'type_user' => 3,
                'type_person' => 4,
                'phone' => '7291623408',
                'collaborator_number' => '250852',
                'birth_date' => '2003-12-27',
                'curp' => 'EIML031227HMCSRSA3',
                'rfc' => 'EIML031227HMC',
                'razon_social' => null,
                'representante_legal' => null,
                'domicilio_fiscal' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'password' => Hash::make('password'),
            ],
            [
                'id' => 374,
                'name' => 'Javier',
                'first_last_name' => 'Rodriguez',
                'second_last_name' => 'Murrieta',
                'email' => 'javier.rodriguez@ldrsolutions.com.mx',
                'type_user' => 6,
                'type_person' => 4,
                'phone' => '3316026901',
                'collaborator_number' => '240374',
                'birth_date' => '1964-05-06',
                'curp' => 'ROMJ640506HPLDRV02',
                'rfc' => 'ROMJ640506DA3',
                'razon_social' => null,
                'representante_legal' => null,
                'domicilio_fiscal' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'password' => Hash::make('password'),
            ],
            [
                'id' => 881,
                'name' => 'Omar Isaac',
                'first_last_name' => 'Valadez',
                'second_last_name' => 'Gregorio',
                'email' => 'omar.valadez@ldrsolutions.com.mx',
                'type_user' => 1,
                'type_person' => 4,
                'phone' => '5525286902',
                'collaborator_number' => '250866',
                'birth_date' => '1986-07-23',
                'curp' => 'VAGO860723HMCLRM04',
                'rfc' => 'VAGO860723HF5',
                'razon_social' => null,
                'representante_legal' => null,
                'domicilio_fiscal' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'password' => Hash::make('password'),
            ],
            [
                'id' => 882,
                'name' => 'Jorge',
                'first_last_name' => 'Heredia',
                'second_last_name' => 'Amaro',
                'email' => 'jorge.amaro@ldrsolutions.com.mx',
                'type_user' => 2,
                'type_person' => 4,
                'phone' => '3322547000',
                'collaborator_number' => '250867',
                'birth_date' => '1966-11-28',
                'curp' => 'HEAJ661128HDFRMR05',
                'rfc' => 'HEAJ661128192',
                'razon_social' => null,
                'representante_legal' => null,
                'domicilio_fiscal' => null,
                'created_at' => now(),
                'updated_at' => now(),
                'password' => Hash::make('password'),
            ],
        ]);
    }
}
